### ISSUE TITLE
Make a script to make a list of all the AWS services

### ISSUE THREAD

**Issue by davidgatti** [0x4447-setup/0x4447_docker#38]
Using this [blog](https://aws.amazon.com/blogs/aws/new-query-for-aws-regions-endpoints-and-more-using-aws-systems-manager-parameter-store/) post, come up with a script that will list all the AWS Prodcuts and make a JSON like this one: [services.json.zip](https://github.com/0x4447-setup/0x4447_docker/files/7448272/services.json.zip)

**Comment by vladpona** [comment]
Can you please tell me where from you got that `services.json.zip`?
There are few problems with the task...
1. The JSON format is mistaken. Right format is:
`[ {}, {}, ..., {} ]`
In the zip:
`{ key: {}, key: {}, ..., key: {} }`
It's readable. But will be big pain for any automation
2. The script in the blog post based on the `aws` console tool. But before usage that tool must be configured with userid, key etc. I'm not sure if there possible to do auto configuration of `aws` console tool. I think on some stage that will ask user to enter email or account confirmation by url via browser etc.
3. I've dag for possibility of service `description, name, image...` obtaining by AWS API. But I can't find any command/subcommand to obtain the list of parameters offered in `services.json.zip`. I can dig deeper. But need to have instructions for points #1 and #2 before

**Comment by davidgatti** [comment]
1. Did check the file and it looks valid to me. It is an object with keys inside it. You can easily loop over an object like this. Any web developer is working with files like this no problem.
2. I need to make a special User for you and give you an API Key and Secret - will give shortly
3. Sorry I did not explain the issue to well. I just need the name of the services, and description if possible. Every other key can be empty.

**Comment by vladpona** [comment]
Ok. Config of that IAM user works fine inside of Docker image. But I'm getting access problem:

`An error occurred (AccessDeniedException) when calling the GetParametersByPath operation: User: arn:aws:iam::239748505547:user/p_aws_marketplace_services_access is not authorized to perform: ssm:GetParametersByPath on resource: arn:aws:ssm:us-east-1::parameter/aws/service/global-infrastructure/regions because no identity-based policy allows the ssm:GetParametersByPath action`

**Comment by davidgatti** [comment]
@vladpona Updated the policy, see if now it works.

**Comment by vladpona** [comment]
Unfortunately all info which possible to collect by that blog post it's "service name" and "long service name" (
If you have any idea how to get service description by name - please let me know
For the moment at `services.json` only 2 parameters
